CREATE USER GYM IDENTIFIED BY GYM;
GRANT CONNECT, RESOURCE TO GYM;

DROP TABLE GYM;
CREATE TABLE GYM_MEM(
    MEM_NO NUMBER PRIMARY KEY,                   -- 회원번호
    MEM_NAME VARCHAR(20) NOT NULL,               -- 회원명
    BIRTH VARCHAR2(10) NOT NULL,                -- 생년월일
    GENDER CHAR(1) DEFAULT 'F' CHECK(GENDER IN ('M','F')), -- 성별
    HEIGHT VARCHAR2(5),                         -- 키
    WEIGHT VARCHAR2(5),                         -- 몸무게
    PT CHAR(1) DEFAULT 'N' CHECK(PT IN ('Y','N')),      -- PT등록여부
    TEACHER VARCHAR2(20),                               -- 담당트레이너
    VIP VARCHAR2(9) DEFAULT 'BRONZE' CHECK(VIP IN ('GOLD', 'SILVER', 'BRONZE')), -- 등급
    ENROLL_DATE DATE DEFAULT SYSDATE,           -- 회원가입일
    END_DATE DATE NOT NULL                      -- 회원등록권종료일
);

DROP SEQUENCE SEQ_MEMNO;
CREATE SEQUENCE SEQ_MEMNO NOCACHE;
ALTER TABLE GYM_MEM MODIFY GENDER CHAR(3) DEFAULT '여' CHECK(GENDER IN ('남','여'));
ALTER TABLE GYM_MEM DROP CONSTRAINT SYS_C007436;

COMMENT ON COLUMN GYM_MEM.MEM_NO IS '회원번호';
COMMENT ON COLUMN GYM_MEM.MEM_NAME IS '회원명';
COMMENT ON COLUMN GYM_MEM.BIRTH IS '생년월일';
COMMENT ON COLUMN GYM_MEM.GENDER IS '성별';
COMMENT ON COLUMN GYM_MEM.HEIGHT IS '키';
COMMENT ON COLUMN GYM_MEM.WEIGHT IS '몸무게';
COMMENT ON COLUMN GYM_MEM.PT IS 'PT등록여부';
COMMENT ON COLUMN GYM_MEM.TEACHER IS '담당트레이너';
COMMENT ON COLUMN GYM_MEM.VIP IS '등급';
COMMENT ON COLUMN GYM_MEM.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN GYM_MEM.END_DATE IS '회원등록권종료일';

SELECT * FROM GYM_MEM;

INSERT INTO GYM_MEM(MEM_NO, MEM_NAME, BIRTH, GENDER, END_DATE) VALUES(SEQ_MEMNO, '김한서', '94/08/01', '남', 2022/12/12);

DELETE FROM GYM_MEM WHERE MEM_NO = '' AND MEM_NAME = '';

INSERT
		  INTO GYM_MEM
		  	   (
		  		  MEM_NO
		  		, MEM_NAME
		  		, BIRTH
		  		, GENDER
		  		, END_DATE
		  		) 
	    VALUES 
	    	   (
	    		SEQ_MEMNO.NEXTVAL
	    	  , '김현이'
	    	  , '89/07/03'
	    	  , '여'
	    	  , '2023/03/12'
	    	  );
commit;

SELECT 
			   MEM_NO
			 , MEM_NAME
			 , BIRTH
			 , GENDER
			 , HEIGHT
			 , WEIGHT
			 , PT
			 , TEACHER
			 , VIP
			 , ENROLL_DATE
			 , END_DATE
		  FROM GYM_MEM
		 WHERE MEM_NAME LIKE '%김%';
         
         UPDATE 
			   GYM_MEM 
		   SET 
		   	   HEIGHT = '189'
		     , WEIGHT = '80'
		     , PT = 'Y'
		     , TEACHER = '김지구'
		     , VIP = 'BRONZE'
		 WHERE MEM_NO = 8;

