CREATE USER GYM IDENTIFIED BY GYM;
GRANT CONNECT, RESOURCE TO GYM;

DROP TABLE GYM;
CREATE TABLE GYM_MEM(
    MEM_NO NUMBER PRIMARY KEY,                   -- 회원번호
    MEM_NAME VARCHAR(20) NOT NULL,               -- 회원명
    BIRTH VARCHAR2(10) NOT NULL,                -- 생년월일
    GENDER CHAR(1) CHECK(GENDER IN ('M','F')) NOT NULL, -- 성별
    HEIGHT VARCHAR2(5),                         -- 키
    WEIGHT VARCHAR2(5),                         -- 몸무게
    PT CHAR(1) DEFAULT 'N' CHECK(PT IN ('Y','N')),      -- PT등록여부
    TEACHER VARCHAR2(20),                               -- 담당트레이너
    VIP VARCHAR2(9) DEFAULT 'BRONZE' CHECK(VIP IN ('GOLD', 'SILVER', 'BRONZE')), -- 등급
    ENROLL_DATE DATE DEFAULT SYSDATE,           -- 회원가입일
    END_DATE DATE NOT NULL                      -- 회원등록권종료일
);

COMMENT ON COLUMN GYM_MEM.MEM_NO IS '회원번호';
COMMENT ON COLUMN GYM_MEM.MEM_NAME IS '회원명';
COMMENT ON COLUMN GYM_MEM.BIRTH IS '생년월일';
COMMENT ON COLUMN GYM_MEM.GENDER IS '성별';
COMMENT ON COLUMN GYM_MEM.HEIGHT IS '키';
COMMENT ON COLUMN GYM_MEM.WEIGHT IS '몸무게';
COMMENT ON COLUMN GYM_MEM.PT IS 'PT등록여부';
COMMENT ON COLUMN GYM_MEM.TEACHER IS '담당트레이너';
COMMENT ON COLUMN GYM_MEM.VIP IS '등급';
COMMENT ON COLUMN GYM_MEM.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN GYM_MEM.END_DATE IS '회원등록권종료일';






